#LOGIN - email which doesnt exist 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "hello762@gmail.com",
    "password": "sachin12345678"
}

###

#LOGIN - incorrect password, correct email 

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "hello612@gmail.com",
    "password": "sa2chin12345678"
}

###

#LOGIN - correct password, correct email /make sure u have created this user in the db
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "hello612@gmail.com",
    "password": "sachin12345678"
}

###

#REGISTER - create a user, email isnt configured yet but should create OTP request
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    
    "email": "hello1233@gmail.com",
    "password": "123456" , 
    "role" : "guest"
}

###
POST http://localhost:3000/auth/verify-otp
Content-Type: application/json

{
    "email": "hello123@gmail.com",
    "otp": "g6fb2w" , 
    "role" : "guest"
}