###Route for testing send message functionality
POST http://localhost:3000/message/send/6677b440ceb4d10a38fe8d61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhjZTZmYWQzYjhiYzFkOGZlNDhjYzgiLCJlbWFpbCI6Imd1ZXN0dGVzdEBnbWFpbC5jb20iLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3MjA1MTAyMDIsImV4cCI6MTcyMDU5NjYwMn0.eEQQpLDSQX9nt75jme1FNWfcLX580rLET6vw2U4SQsE
Content-Type: application/json

{
    "message" : "This is the Second message to host 6677b440ceb4d10a38fe8d61."
}


###Route for testing get messages functionality
GET http://localhost:3000/message/6677b440ceb4d10a38fe8d61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhjZTZmYWQzYjhiYzFkOGZlNDhjYzgiLCJlbWFpbCI6Imd1ZXN0dGVzdEBnbWFpbC5jb20iLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3MjA1MTAyMDIsImV4cCI6MTcyMDU5NjYwMn0.eEQQpLDSQX9nt75jme1FNWfcLX580rLET6vw2U4SQsE

###Get Contact
GET http://localhost:3000/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhjZTZmYWQzYjhiYzFkOGZlNDhjYzgiLCJlbWFpbCI6Imd1ZXN0dGVzdEBnbWFpbC5jb20iLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3MjA1MTAyMDIsImV4cCI6MTcyMDU5NjYwMn0.eEQQpLDSQX9nt75jme1FNWfcLX580rLET6vw2U4SQsE