### no longer in use
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "hello612@gmail.com",
    "password": "sachin12345678", 
    "role": "user"
}



### Get user (Self) info // Signin using auth routes and replace the token
GET http://localhost:3000/properties/host-properties
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc1Yjk0ZDBiYzBiOWJlMGEyOTZiMTkiLCJlbWFpbCI6ImhAZ21haWwuY29tIiwicm9sZSI6Imhvc3QiLCJpYXQiOjE3MTk2NDM1MDksImV4cCI6MTcxOTcyOTkwOX0.yMg3IC6ItSh0-SqZ8a_J2xrc5SSbKMbTXvGL41M5_eo	
